package buisness;
// Generated 30.10.2016 16:42:46 by Hibernate Tools 4.3.1




/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String desc;
     private int price;
     private String isbn;
     private String author;
     private String genre;
     private int year;
     private String lang;
     private String house;
     private int stock;
     
    public Book() {
    }

    public Book(String bookCode, String bookDesc, int bookPrice, String bookIsbn, String bookAuthor, String bookGenre, int bookYear, String bookLang, String bookHouse, int stock) {
       this.desc = bookDesc;
       this.price = bookPrice;
       this.isbn = bookIsbn;
       this.author = bookAuthor;
       this.genre = bookGenre;
       this.year = bookYear;
       this.lang = bookLang;
       this.house = bookHouse;
       this.stock = stock;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer bookId) {
        this.id = bookId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
    
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String bookDesc) {
        this.desc = bookDesc;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int bookPrice) {
        this.price = bookPrice;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String bookIsbn) {
        this.isbn = bookIsbn;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String bookAuthor) {
        this.author = bookAuthor;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String bookGenre) {
        this.genre = bookGenre;
    }
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int bookYear) {
        this.year = bookYear;
    }
    public String getLang() {
        return this.lang;
    }
    
    public void setLang(String bookLang) {
        this.lang = bookLang;
    }
    public String getHouse() {
        return this.house;
    }
    
    public void setHouse(String bookHouse) {
        this.house = bookHouse;
    }

    public int getStock() {
        return stock;
    }

    public void setStock(int stock) {
        this.stock = stock;
    }


}


