package buisness;
// Generated 23.10.2016 16:16:44 by Hibernate Tools 4.3.1



/**
 * Books generated by hbm2java
 */
public class Books  implements java.io.Serializable {
     private static final String ITEM_PATH = "items/";

     private Integer id;
     private String title;
     private String desc;
     private String isbn;
     private String image;
     private double price;
     private String author;
     private short pageCount;
     private short stock;

    public Books() {
    }

    public Books(String title, String desc, String isbn, String image, double price, String author, short pageCount, short stock) {
       this.title = title;
       this.desc = desc;
       this.isbn = isbn;
       this.image = image;
       this.price = price;
       this.author = author;
       this.pageCount = pageCount;
       this.stock = stock;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getImage() {
        if(!this.image.equals("")) {
            return ITEM_PATH + this.image;
        }
        
        return ITEM_PATH + "noimage.jpg";
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public short getPageCount() {
        return this.pageCount;
    }
    
    public void setPageCount(short pageCount) {
        this.pageCount = pageCount;
    }
    public short getStock() {
        return this.stock;
    }
    
    public void setStock(short stock) {
        this.stock = stock;
    }




}


