package buisness;
// Generated 30.10.2016 16:42:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String firstName;
     private String lastName;
     private String fatherName;
     private String email;
     private String country;
     private String district;
     private String city;
     private String address;
     private String zip;
     private String creditCardType;
     private String creditCardNumber;
     private String creditCardExp;
     private Set<Invoice> invoices = new HashSet<Invoice>(0);

    public User() {
    }

    public User(String firstName, String lastName, String fatherName, String email, String country, String district, String city, String address, String zip, String creditCardType, String creditCardNumber, String creditCardExp, Set<Invoice> invoices) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.fatherName = fatherName;
       this.email = email;
       this.country = country;
       this.district = district;
       this.city = city;
       this.address = address;
       this.zip = zip;
       this.creditCardType = creditCardType;
       this.creditCardNumber = creditCardNumber;
       this.creditCardExp = creditCardExp;
       this.invoices = invoices;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getFatherName() {
        return this.fatherName;
    }
    
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    public String getCreditCardType() {
        return this.creditCardType;
    }
    
    public void setCreditCardType(String creditCardType) {
        this.creditCardType = creditCardType;
    }
    public String getCreditCardNumber() {
        return this.creditCardNumber;
    }
    
    public void setCreditCardNumber(String creditCardNumber) {
        this.creditCardNumber = creditCardNumber;
    }
    public String getCreditCardExp() {
        return this.creditCardExp;
    }
    
    public void setCreditCardExp(String creditCardExp) {
        this.creditCardExp = creditCardExp;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }




}


